#!/bin/bash

# tablet_toggle toggles the laptop into tablet mode.
# It assumes you only have on screen, so if you plug into an external monitor
# things might get weird.

out=`swaymsg -pt get_outputs | awk '/Output/{print $2}'`
if [ $1 = "on" ]; then
	swaymsg output $out transform 90
else
	swaymsg output $out transform 0
fi
swaymsg "input * map_to_output $out" #re-map to rotate touchpad
